#AULA 1 - NAO TEVE ATIVIDADE

In [ ]:
#Script para mover/copiar arquivos
import os, shutil

entrada = r'C:\Users\shirleyps\Desktop\Entrada'
saida = r'C:\Users\Shirley\Downloads\teste'

for file in os.listdir(entrada):
	shutil.move(os.path.join(entrada,file), os.path.join(saida,file))

# AULA 2 - ATIVIDADE

**Os exercícios devem ser colocado em um repositória Git público e a URL do projeto deve ser enviada para: pablo.bizzi@gmail.com e compartilhar o repositório no Github. Meu usuário é pablobizzi**

1 - Faça um algoritmo que solicite ao usuário números e os armazene em um vetor de 5 posições. Crie uma função que recebe o vetor preenchido e substitua todas as ocorrência de valores positivos por 1 e todos os valores negativos por 0.

In [ ]:
def vetor():
  import numpy as np 
  vetor = [0]*5
  for n in range(5):
    f = int(input('Digite um número: '))
    vetor[n] = f
  array = np.array(vetor)
  print(array)
  for n in range(5):
    if array[n] < 0:
      array[n] = 0
    else:
      array[n] =1
  print(array)
vetor()

2 - Faça um algoritmo que solicita 2 arrays diferentes de 3 posições que irão representar as 3 notas de 2 alunos da instituição. Após isso, faça a média do somatório de todos os valores dos dois arrays.

In [ ]:
import numpy as np 
aluno1 = [0]*3
aluno2 = [0]*3
for n in range(3):
  n1 = int(input(f'1° Aluno: Informe a {n+1}° nota: '))
  aluno1[n] = n1
aluno1 = np.array(aluno1)
for n in range(3):
  n2 = int(input(f'2° Aluno: Informe a {n+1}° nota: '))
  aluno2[n] = n2
aluno2 = np.array(aluno2)

print(aluno1)
print(aluno2)
print(f'A media geral é {round(sum(aluno1+aluno2)/(aluno1.size+aluno2.size)),2}')

# AULA 3 - ATIVIDADE

1° GERE UMA MATRIZ COM VALORES ALEATÓRIOS INTEIROS E FAÇA UMA FUNÇÃO QUE RETORNE A SOMA DOS ELEMENTOS DA DIAGONAL PRINCIPAL DE UMA MATRIZ 5X5

In [ ]:
import numpy as np
matriz = np.random.randint(0,1000,(5,5))
print(matriz)
np.trace(matriz)

[[848 996 363 134 954]
 [986 909 605 437 878]
 [747 433 808 112 387]
 [383 405 203 339 114]
 [280  32 782 126 651]]


3555

2° CRIE DUAS MATRIZES 4x4 COM VALORES ALEATÓRIOS INTEIROS. APÓS ISSO, CALCULE A SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO, DIVISÃO E VERIFIQUE A IGUALDADE ENTRE AS MATRIZES

In [ ]:
import numpy as np
matriz1 = np.random.randint(0,1000,(4,4))
matriz2 = np.random.randint(0,1000,(4,4))

print(f'{matriz1}\n \n {matriz2}')

soma = matriz1+matriz2
print(soma)

sub = matriz1-matriz2
print(sub)

mult = matriz1*matriz2
print(mult)

div = np.round(matriz1/matriz2,2)
print(div)

igualdade = matriz1==matriz2
print(igualdade)


In [ ]:
#2PROFESSOR LUCAS

import numpy as np

matriz = np.random.randint(100, size = (5, 5))

print(matriz)

def soma_diagonal1(arr):
    return np.trace(arr)

def soma_diagonal2(arr):
    return np.diag(arr).sum()

def soma_diagonal_manual(arr):
    resultado = 0

    n = arr.shape[0]

    for i in range(n):
        resultado += arr[i][i]
    
    return resultado

print("Manual: ",soma_diagonal_manual(matriz))
print("Método 1: ", soma_diagonal1(matriz))
print("Método 2: ", soma_diagonal2(matriz))

[[53 32 77 17 56]
 [99 52 74 81 28]
 [41 13 27 98 91]
 [62 80 63 58 47]
 [35 65 10 21 30]]
Manual:  220
Método 1:  220
Método 2:  220


#AULA 4 - ATIVIDADE

**Passo 1: Abra o CSV do seguinte link:**

https://www.stats.govt.nz/assets/Uploads/Effects-of-COVID-19-on-trade/Effects-of-COVID-19-on-trade-At-15-December-2021-provisional/Download-data/effects-of-covid-19-on-trade-at-15-december-2021-provisional.csv

In [ ]:
# Instalando pandas
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Passo 3: Use o arquivo CSV e o associe a uma variável chamada health.**

In [ ]:
# importanto a biblioteca
import pandas as pd
health = pd.read_csv('https://www.stats.govt.nz/assets/Uploads/Effects-of-COVID-19-on-trade/Effects-of-COVID-19-on-trade-At-15-December-2021-provisional/Download-data/effects-of-covid-19-on-trade-at-15-december-2021-provisional.csv')

**Passo 4: Veja as 5 primeiras linhas:**

In [ ]:
health.head()

Direction  Year        Date   Weekday Country Commodity Transport_Mode  \
0   Exports  2015  01/01/2015  Thursday     All       All            All   
1   Exports  2015  02/01/2015    Friday     All       All            All   
2   Exports  2015  03/01/2015  Saturday     All       All            All   
3   Exports  2015  04/01/2015    Sunday     All       All            All   
4   Exports  2015  05/01/2015    Monday     All       All            All   

  Measure      Value  Cumulative  
0       $  104000000   104000000  
1       $   96000000   200000000  
2       $   61000000   262000000  
3       $   74000000   336000000  
4       $  105000000   442000000

**Passo 5: Qual o número de observações/linhas nesse dataset?**

In [ ]:
print(health.shape[0])

111438


 **Passo 6: Qual o número de colunas desse dataset?**

In [ ]:
print(health.shape[1])

10


**Passo 7: Imprima o nome de todas as colunas**

In [ ]:
print(health.columns)

**Passo 8: Qual o nome da 3rd coluna?**

In [ ]:
print(health.columns[2])

Date


**Passo 9: Qual o tipo de dado dessa coluna?**

In [ ]:
print(health.dtypes['Date'])

object


**Passo 10: Como são os índices do dataset?**



In [ ]:
print(health.index)

RangeIndex(start=0, stop=111438, step=1)


**Passo 11: Qual o nome do produto na 19th observação?**

In [ ]:
(health.loc[[18],['Value']])

Value
18  164000000

#AULA 5 - ATIVIDADE

**Questão 1 - Consultar duas base de dados da Netflix para descobrir quais filmes e séries são mais populares no mundo e também no Brasil.**


Lista dos mais populares: https://top10.netflix.com/data/most-popular.xlsx

Lista dos mais populares por Países: https://top10.netflix.com/data/all-weeks-countries.xlsx

In [ ]:
!pip install pandas
import pandas as pd

**Analisando os dados**

In [ ]:
MPM = pd.read_excel('https://top10.netflix.com/data/most-popular.xlsx')
MPM.head(1)

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


category  rank  show_title season_title  hours_viewed_first_28_days
0  Films (English)     1  Red Notice          NaN                   364020000

In [ ]:
MPM.head(1)

category  rank  show_title season_title  hours_viewed_first_28_days
0  Films (English)     1  Red Notice          NaN                   364020000

In [ ]:
MPM['show_title'].unique()

array(['Red Notice', "Don't Look Up", 'Bird Box', 'The Gray Man',
       'The Adam Project', 'Extraction', 'Purple Hearts',
       'The Unforgivable', 'The Irishman', 'The Kissing Booth 2',
       'Blood Red Sky', 'The Platform', 'Black Crab', 'Through My Window',
       'The Takedown', 'Below Zero', 'Rogue City', 'Carter',
       'The Forgotten Battle', 'Restless', 'Stranger Things',
       'Bridgerton', 'Lucifer', 'The Witcher', 'Inventing Anna',
       '13 Reasons Why', 'Ozark', 'Squid Game', 'Money Heist',
       'All of Us Are Dead', 'Extraordinary Attorney Woo',
       'Café con aroma de mujer', 'Lupin', 'Elite', 'Who Killed Sara?'],
      dtype=object)

In [ ]:
MPM.duplicated().sum()

0

In [ ]:
MPM.shape

(40, 5)

In [ ]:
MPM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   category                    40 non-null     object
 1   rank                        40 non-null     int64 
 2   show_title                  40 non-null     object
 3   season_title                20 non-null     object
 4   hours_viewed_first_28_days  40 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1.7+ KB


In [ ]:
MPM.isnull().sum()

category                       0
rank                           0
show_title                     0
season_title                  20
hours_viewed_first_28_days     0
dtype: int64

In [ ]:
MPP = pd.read_excel('https://top10.netflix.com/data/all-weeks-countries.xlsx')
MPP.head(1)

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


country_name country_iso2        week category  weekly_rank     show_title  \
0    Argentina           AR  2022-09-04    Films            1  Loving Adults   

  season_title  cumulative_weeks_in_top_10  
0          NaN                           2

In [ ]:
MPP['country_name'].unique()

array(['Argentina', 'Australia', 'Austria', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Belgium', 'Bolivia', 'Brazil', 'Bulgaria', 'Canada',
       'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Estonia', 'Finland', 'France', 'Germany',
       'Greece', 'Guadeloupe', 'Guatemala', 'Honduras', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Ireland', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Kuwait', 'Latvia',
       'Lebanon', 'Lithuania', 'Luxembourg', 'Malaysia', 'Maldives',
       'Malta', 'Martinique', 'Mauritius', 'Mexico', 'Morocco',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Réunion', 'Saudi Arabia', 'Serbia', 'Singapore',
       'Slovakia', 'Slovenia

In [ ]:
MPP.shape

(116020, 8)

In [ ]:
MPP.isnull().sum()

country_name                      0
country_iso2                      0
week                              0
category                          0
weekly_rank                       0
show_title                        0
season_title                  59592
cumulative_weeks_in_top_10        0
dtype: int64

In [ ]:
filmes = MPP.groupby('country_name')['country_name'].count()
filmes

country_name
Argentina         1240
Australia         1240
Austria           1240
Bahamas           1240
Bahrain           1240
                  ... 
United Kingdom    1240
United States     1240
Uruguay           1240
Venezuela         1240
Vietnam           1240
Name: country_name, Length: 94, dtype: int64

**Filtrando Filmes Coutry Name Brasil**

In [ ]:
MP_B = MPP[MPP['country_name'] == 'Brazil']
MP_B.head()

country_name country_iso2        week category  weekly_rank  \
9920       Brazil           BR  2022-09-04    Films            1   
9921       Brazil           BR  2022-09-04    Films            2   
9922       Brazil           BR  2022-09-04    Films            3   
9923       Brazil           BR  2022-09-04    Films            4   
9924       Brazil           BR  2022-09-04    Films            5   

             show_title season_title  cumulative_weeks_in_top_10  
9920          Fenced In          NaN                           1  
9921      Loving Adults          NaN                           2  
9922  Love in the Villa          NaN                           1  
9923            Me Time          NaN                           2  
9924          I Came By          NaN                           1

In [ ]:
MP_B['show_title'].unique()
MP_B['show_title'].duplicated().sum()

751

In [ ]:
MP_B.shape

(1240, 8)

**Populares apenas no Brasil**

In [ ]:
filtro = MP_B.groupby('show_title')['show_title'].count().sort_values(ascending=False)
filtro

show_title
Chiquititas                53
As Aventuras de Poliana    37
Carinha de Anjo            36
Stranger Things            31
Carrossel                  30
                           ..
Silver Skates               1
Fenced In                   1
Skylines                    1
Fatherhood                  1
أصحاب ...ولا أعزّ           1
Name: show_title, Length: 489, dtype: int64

**Populares apenas no Brasil e no MUNDO**

In [ ]:
MP_B_M = MPM.merge(MP_B, how="inner", on='show_title')
MP_B_M.head(20)
MP_B_M.shape

(245, 12)

In [ ]:
filtro2 = MP_B_M.groupby('show_title')['show_title'].count().sort_values(ascending=False)
filtro2

show_title
Stranger Things               62
Money Heist                   39
Café con aroma de mujer       23
Bridgerton                    18
The Witcher                   16
Squid Game                    10
Red Notice                     6
Extraordinary Attorney Woo     6
Inventing Anna                 6
All of Us Are Dead             5
Lucifer                        5
Elite                          5
Don't Look Up                  5
Through My Window              5
The Gray Man                   4
Purple Hearts                  4
The Adam Project               4
The Unforgivable               3
Black Crab                     3
Restless                       3
The Takedown                   3
Who Killed Sara?               2
The Forgotten Battle           2
Carter                         2
Blood Red Sky                  2
Lupin                          1
Ozark                          1
Name: show_title, dtype: int64

In [ ]:
MP_B_M['show_title'].duplicated().sum()

218

**RETIRNAD AS DUPLICATAS, HA 27 FILMES QUE ESTAO NA LISTA DOS FIMLES MASI POPULARES DO MUNDO E TAMBEM CONSTAM NA LISTA DOS MAIS POPULARES DO BRASIL**

In [ ]:
MP_B_M['show_title'].unique()

array(['Red Notice', "Don't Look Up", 'The Gray Man', 'The Adam Project',
       'Purple Hearts', 'The Unforgivable', 'Blood Red Sky', 'Black Crab',
       'Through My Window', 'The Takedown', 'Carter',
       'The Forgotten Battle', 'Restless', 'Stranger Things',
       'Bridgerton', 'Lucifer', 'The Witcher', 'Inventing Anna', 'Ozark',
       'Squid Game', 'Money Heist', 'All of Us Are Dead',
       'Extraordinary Attorney Woo', 'Café con aroma de mujer', 'Lupin',
       'Elite', 'Who Killed Sara?'], dtype=object)

In [ ]:
SEM_DUPLICATAS = MP_B_M.drop_duplicates('show_title')
SEM_DUPLICATAS.shape

(27, 12)

#AULA 6 - ATIVIDADE

**ATIVIDADE 1 - Faça o que se pede com a base de dados mpg, ao finalizar todas as etapas, envie o link do GitHub por e-mail para:** pablo.bizzi@gmail.com

Dicionário dos dados:

* mpg --> consumo do carro
* cylinders --> quantidade de cilindros
* displacement --> deslocamento com um tanque
* horsepower --> potência do carro
* weight --> peso do carro
* acceleration --> aceleração do carro
* model_year --> modelo ano do carro
* origin --> origem do carro
* name --> nome do carro

**Carregar a base de dados**

In [ ]:
# importanto a biblioteca
import pandas as pd

mpg = pd.read_csv('sample_data/mpg.csv', delimiter=',')

mpg.shape

(398, 9)

**Principais caracteristicas dos dados (tipo, tamanho e outras informações relevantes)**

In [ ]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


**Descritivo das variáveis numéricas**

In [ ]:
mpg.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

**Soma e percentual dos dados faltantes**

In [ ]:
mpg.isnull().sum()
mpg.isnull().sum()*100/mpg.shape[0]

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      1.507538
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

**Soma e percentual dos dados não nulos**

In [ ]:
mpg.notna().sum()
mpg.notna().sum()*100/mpg.shape[0]

mpg             100.000000
cylinders       100.000000
displacement    100.000000
horsepower       98.492462
weight          100.000000
acceleration    100.000000
model_year      100.000000
origin          100.000000
name            100.000000
dtype: float64

**Deletar as linhas com valores nulos**

In [ ]:
mpg2 = mpg.dropna()
mpg2.shape

(392, 9)

**Deletar a coluna ano modelo (model_year)**

In [ ]:
mpg2 = mpg2.drop(columns='model_year')
mpg2

mpg  cylinders  displacement  horsepower  weight  acceleration  origin  \
0    18.0          8         307.0       130.0    3504          12.0     usa   
1    15.0          8         350.0       165.0    3693          11.5     usa   
2    18.0          8         318.0       150.0    3436          11.0     usa   
3    16.0          8         304.0       150.0    3433          12.0     usa   
4    17.0          8         302.0       140.0    3449          10.5     usa   
..    ...        ...           ...         ...     ...           ...     ...   
393  27.0          4         140.0        86.0    2790          15.6     usa   
394  44.0          4          97.0        52.0    2130          24.6  europe   
395  32.0          4         135.0        84.0    2295          11.6     usa   
396  28.0          4         120.0        79.0    2625          18.6     usa   
397  31.0          4         119.0        82.0    2720          19.4     usa   

                          name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
2           plymouth satellite  
3                amc rebel sst  
4                  ford torino  
..                         ...  
393            ford mustang gl  
394                  vw pickup  
395              dodge rampage  
396                ford ranger  
397                 chevy s-10  

[392 rows x 8 columns]

**Deletar carros de origem japonesa**

In [ ]:
mpg3 = mpg2[mpg2['origin'] !='japan']
mpg3.head() 

mpg  cylinders  displacement  horsepower  weight  acceleration origin  \
0  18.0          8         307.0       130.0    3504          12.0    usa   
1  15.0          8         350.0       165.0    3693          11.5    usa   
2  18.0          8         318.0       150.0    3436          11.0    usa   
3  16.0          8         304.0       150.0    3433          12.0    usa   
4  17.0          8         302.0       140.0    3449          10.5    usa   

                        name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [ ]:
#mpg3 = mpg2.drop(columns=['origin'] =='japan')
#Pablo, tentei exluir as linhas de acordo com o filtro, utilizando DROP... mas nao consegui, tem como fazer com essa funcao? 
#Como nao consegui com Drop, criei um novo df com o filtro reverso ;) >>>  ['origin'] !='japan'..

**Verificar a quantidade de dados duplicados no dataframe**

In [ ]:
mpg3.duplicated().sum()

0

**Comparar os tamanhos do dataframe original e o modificado**

In [ ]:
print(f' df Origial = {mpg.shape}, e df Modificado = {mpg3.shape}')

 df Origial = (398, 9), e df Modificado = (313, 8)


**Gravar a nova base de dados após a limpeza**

In [ ]:
mpg3.to_csv('mpg3.csv', index = False)

In [ ]:
mpg3.to_excel('mpg3.xlsx', index = False)