# AULA 2 - ATIVIDADE

**Os exercícios devem ser colocado em um repositória Git público e a URL do projeto deve ser enviada para: pablo.bizzi@gmail.com e compartilhar o repositório no Github. Meu usuário é pablobizzi**

1 - Faça um algoritmo que solicite ao usuário números e os armazene em um vetor de 5 posições. Crie uma função que recebe o vetor preenchido e substitua todas as ocorrência de valores positivos por 1 e todos os valores negativos por 0.

In [ ]:
def vetor():
  import numpy as np 
  vetor = [0]*5
  for n in range(5):
    f = int(input('Digite um número: '))
    vetor[n] = f
  array = np.array(vetor)
  print(array)
  for n in range(5):
    if array[n] < 0:
      array[n] = 0
    else:
      array[n] =1
  print(array)
vetor()

2 - Faça um algoritmo que solicita 2 arrays diferentes de 3 posições que irão representar as 3 notas de 2 alunos da instituição. Após isso, faça a média do somatório de todos os valores dos dois arrays.

In [ ]:
import numpy as np 
aluno1 = [0]*3
aluno2 = [0]*3
for n in range(3):
  n1 = int(input(f'1° Aluno: Informe a {n+1}° nota: '))
  aluno1[n] = n1
aluno1 = np.array(aluno1)
for n in range(3):
  n2 = int(input(f'2° Aluno: Informe a {n+1}° nota: '))
  aluno2[n] = n2
aluno2 = np.array(aluno2)

print(aluno1)
print(aluno2)
print(f'A media geral é {round(sum(aluno1+aluno2)/(aluno1.size+aluno2.size)),2}')

# AULA 3 - ATIVIDADE

1° GERE UMA MATRIZ COM VALORES ALEATÓRIOS INTEIROS E FAÇA UMA FUNÇÃO QUE RETORNE A SOMA DOS ELEMENTOS DA DIAGONAL PRINCIPAL DE UMA MATRIZ 5X5

In [17]:
import numpy as np
matriz = np.random.randint(0,1000,(5,5))
print(matriz)
np.trace(matriz)

[[287 717 354 984 932]
 [393 383 162 803 446]
 [896 508 846 290 665]
 [ 36 952 309 354 247]
 [556 473 116 303 915]]


2785

2° CRIE DUAS MATRIZES 4x4 COM VALORES ALEATÓRIOS INTEIROS. APÓS ISSO, CALCULE A SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO, DIVISÃO E VERIFIQUE A IGUALDADE ENTRE AS MATRIZES

In [37]:
import numpy as np
matriz1 = np.random.randint(0,1000,(4,4))
matriz2 = np.random.randint(0,1000,(4,4))

print(f'{matriz1}\n \n {matriz2}')

soma = matriz1+matriz2
print(soma)

sub = matriz1-matriz2
print(sub)

mult = matriz1*matriz2
print(mult)

div = np.round(matriz1/matriz2,2)
print(div)


[[174 962 183  44]
 [434 546 163 215]
 [527 541 755  17]
 [360 265 719 827]]
 
 [[267 748 186 775]
 [348 472 843 427]
 [639 349 833 470]
 [562 571 654   1]]
[[ 441 1710  369  819]
 [ 782 1018 1006  642]
 [1166  890 1588  487]
 [ 922  836 1373  828]]
[[ -93  214   -3 -731]
 [  86   74 -680 -212]
 [-112  192  -78 -453]
 [-202 -306   65  826]]
[[ 46458 719576  34038  34100]
 [151032 257712 137409  91805]
 [336753 188809 628915   7990]
 [202320 151315 470226    827]]
[[6.50e-01 1.29e+00 9.80e-01 6.00e-02]
 [1.25e+00 1.16e+00 1.90e-01 5.00e-01]
 [8.20e-01 1.55e+00 9.10e-01 4.00e-02]
 [6.40e-01 4.60e-01 1.10e+00 8.27e+02]]
