# AULA 2 - ATIVIDADE

**Os exercícios devem ser colocado em um repositória Git público e a URL do projeto deve ser enviada para: pablo.bizzi@gmail.com e compartilhar o repositório no Github. Meu usuário é pablobizzi**

1 - Faça um algoritmo que solicite ao usuário números e os armazene em um vetor de 5 posições. Crie uma função que recebe o vetor preenchido e substitua todas as ocorrência de valores positivos por 1 e todos os valores negativos por 0.

In [ ]:
def vetor():
  import numpy as np 
  vetor = [0]*5
  for n in range(5):
    f = int(input('Digite um número: '))
    vetor[n] = f
  array = np.array(vetor)
  print(array)
  for n in range(5):
    if array[n] < 0:
      array[n] = 0
    else:
      array[n] =1
  print(array)
vetor()

2 - Faça um algoritmo que solicita 2 arrays diferentes de 3 posições que irão representar as 3 notas de 2 alunos da instituição. Após isso, faça a média do somatório de todos os valores dos dois arrays.

In [ ]:
import numpy as np 
aluno1 = [0]*3
aluno2 = [0]*3
for n in range(3):
  n1 = int(input(f'1° Aluno: Informe a {n+1}° nota: '))
  aluno1[n] = n1
aluno1 = np.array(aluno1)
for n in range(3):
  n2 = int(input(f'2° Aluno: Informe a {n+1}° nota: '))
  aluno2[n] = n2
aluno2 = np.array(aluno2)

print(aluno1)
print(aluno2)
print(f'A media geral é {round(sum(aluno1+aluno2)/(aluno1.size+aluno2.size)),2}')

# AULA 3 - ATIVIDADE

1° GERE UMA MATRIZ COM VALORES ALEATÓRIOS INTEIROS E FAÇA UMA FUNÇÃO QUE RETORNE A SOMA DOS ELEMENTOS DA DIAGONAL PRINCIPAL DE UMA MATRIZ 5X5

In [17]:
import numpy as np
matriz = np.random.randint(0,1000,(5,5))
print(matriz)
np.trace(matriz)

[[287 717 354 984 932]
 [393 383 162 803 446]
 [896 508 846 290 665]
 [ 36 952 309 354 247]
 [556 473 116 303 915]]


2785

2° CRIE DUAS MATRIZES 4x4 COM VALORES ALEATÓRIOS INTEIROS. APÓS ISSO, CALCULE A SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO, DIVISÃO E VERIFIQUE A IGUALDADE ENTRE AS MATRIZES

In [38]:
import numpy as np
matriz1 = np.random.randint(0,1000,(4,4))
matriz2 = np.random.randint(0,1000,(4,4))

print(f'{matriz1}\n \n {matriz2}')

soma = matriz1+matriz2
print(soma)

sub = matriz1-matriz2
print(sub)

mult = matriz1*matriz2
print(mult)

div = np.round(matriz1/matriz2,2)
print(div)

igualdade = matriz1==matriz2
print(igualdade)


[[846 493 154 256]
 [ 29 244 880 836]
 [ 12  64 411 566]
 [309 176 198 113]]
 
 [[454 173 324 515]
 [738 367 122 138]
 [893 503 392 853]
 [155 209 228 140]]
[[1300  666  478  771]
 [ 767  611 1002  974]
 [ 905  567  803 1419]
 [ 464  385  426  253]]
[[ 392  320 -170 -259]
 [-709 -123  758  698]
 [-881 -439   19 -287]
 [ 154  -33  -30  -27]]
[[384084  85289  49896 131840]
 [ 21402  89548 107360 115368]
 [ 10716  32192 161112 482798]
 [ 47895  36784  45144  15820]]
[[1.86 2.85 0.48 0.5 ]
 [0.04 0.66 7.21 6.06]
 [0.01 0.13 1.05 0.66]
 [1.99 0.84 0.87 0.81]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
